### ISSUE TITLE
Improve packaging

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkX#1]
@cancan101 @dnouri I could use your help with getting this ready for prime time.  I'm following this tutorial:

http://python-packaging.readthedocs.io/en/latest/minimal.html

But I am not really up on best practices for maintaining this package.

**Comment by dnouri** [comment]
Thanks for creating this!  It looks good to me.  Let me know if you have anything particular in mind that needs improvement, and I'll be more than happy to try and help.
