### ISSUE TITLE
Update code that uses these modules

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkX#2]
With these modules installed, client code should

    from thinkx import thinkstats2

For example, rather than

    import thinkstats2

I might update the code to try one and then the other.

**Comment by dnouri** [comment]
You might want to consider setting up your modules using `py_modules` to make them available global as opposed to inside a `thinkx` package.  The use of `py_modules` in the call to `setup` [as it's used here](https://github.com/AllenDowney/ThinkStats2/blob/master/code/setup.py#L9) would allow your users to still import your code like this:

```python
import thinkstats  # etc
```

So no changes required w.r.t. the code that's used in the books and elsewhere.

**Comment by AllenDowney** [comment]
@dnouri Yes, that would be better, but it's not working for me.  I just pushed 1612d70 with a version of setup.py that uses py_modules instead of packages.  When I try installing it locally, like this

    python setup.py develop

It seems to succeed.  But then I can't import any of the modules directly; I still have to specify thinkx.  Maybe I have residual files from the previous install?

**Comment by AllenDowney** [comment]
This seems to be working now.  I just pushed it to PyPI.  Thanks again!
